version: '3.8'

services:
  bouncer:
    build: .
    container_name: bouncer_seguro
    restart: always
    ports:
      - "9999:80"
    environment:
      - BOUNCER_USER=${BOUNCER_USER}
      - BOUNCER_PASS=${BOUNCER_PASS}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN}
      - BOUNCER_TOTP_SECRET=${BOUNCER_TOTP_SECRET}
    volumes:
      - ./config.json:/root/config.json:rw
      - ./data:/root/data:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
