services:
  regio:
    build: .
    container_name: REGIO_seguro
    restart: always
    ports:
      - "9999:80"
    env_file:
      - .env
    volumes:
      - ./config.json:/root/config.json:rw
      - ./data:/root/data:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
